server.port=8081
spring.application.name=auth-service
spring.datasource.url=${DB_AUTH_URL:jdbc:postgresql://localhost:5432/skillsync_auth}
spring.datasource.username=${DB_AUTH_USER:postgres}
spring.datasource.password=${DB_AUTH_PW:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
springdoc.api-docs.path=/auth/v3/api-docs
springdoc.api-docs.enabled=true

# Critical Fix: Enable Forwarded Headers (X-Forwarded-Host, etc.)
server.forward-headers-strategy=FRAMEWORK
# Fallback Server URL for Swagger
springdoc.api-docs.servers[0].url=http://localhost:8080
springdoc.api-docs.servers[0].description=API Gateway
