spring.application.name=review-service
server.port=8088
spring.datasource.url=${DB_REVIEW_URL:jdbc:postgresql://localhost:5432/skillsync_review_db}
spring.datasource.username=${DB_REVIEW_USER:postgres}
spring.datasource.password=${DB_REVIEW_PW:root}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
springdoc.api-docs.path=/reviews/v3/api-docs
springdoc.api-docs.enabled=true

server.forward-headers-strategy=FRAMEWORK
springdoc.api-docs.servers[0].url=http://localhost:8080
springdoc.api-docs.servers[0].description=API Gateway
